### PR TITLE
Require `setuptools` needed for `pkg_resources`

### LINKED ISSUE #8: @conda-forge-admin, please re-render
@conda-forge-admin, please re-render.

### PR DESCRIPTION
**Pull request by conda-forge-linter**
This package [depends on `pkg_resources` at runtime]( https://github.com/ronaldoussoren/altgraph/blame/6f5574bb0559a222971ab347dfef9a9dad9b3f1a/altgraph/__init__.py#L142 ). So needs `setuptools` in `requirements/run`. This adds it as a dependency.

<hr>

Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #8.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes #8

### CODE REVIEW

**Comment by jakirkham** [comment]
@conda-forge/altgraph, this is ready for review! 😄

**Review by Anthchirp — APPROVED** [review]
Lgtm thank you!

**Comment by jakirkham** [comment]
Thanks Markus! 😄

**Comment by jakirkham** [comment]
Hotfixing old packages here ( https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/255 )

**Pull request merged**
